Food repository test
pobrok/backend pull request #66
Opened 2022-08-26 13:10 UTC by jVucetic

2022-08-28 12:12 UTC, d-vucetic commented
Unutar baze imam dva admina sa emailom fmadmin@vegait.rs

2022-08-28 12:20 UTC, d-vucetic commented
UserService ima create fake user metod-u kojoj tu nije mjesto. Service layer treba da sadrzi interfejs prema klijent aplikacijama ili neku unutrasnju logiku aplikacije. Za kreiranje objekata unutar test- imamo Faktori klasu ili neki helper metod. Service bi ubacili unutar test-a u slucajevima da zelimo da testiramo ubaceni service. Preporocujem da se procita malo uloga servica i repositoriija da bi bila jasnija konkreno cija je sta odgovornost.

- Factory kreira samo razne tipove objekta i priprema mozda neki od objekata od koji klasa zavisi.
- Service sadrzi operacije koje obavljamo nad externo primljenim podacima, pripremamo ih za persistance layer itd.
- Repository layer je zaduzen za cuvanje konkretnog entiteta.

2022-08-28 12:24 UTC, d-vucetic requested changes

2022-08-28 12:24 UTC, d-vucetic commented on src/test/java/com/g1dra/foodmanager/integration/FoodIntegrationTest.java
> +        System.out.println("before");
Ocisti kod, ja obicno pregledam da nisam ostavio nesto ovoga tipa prije nego sto komitujem

2022-08-28 12:24 UTC, d-vucetic commented on src/test/java/com/g1dra/foodmanager/integration/UserIntegrationTest.java
> +    public User getUser()
Nejasno imenovanje, extractovati u factory klasu koja je zaduzena za pravljenja svih oblika User-a

2022-08-30 12:30 UTC, jVucetic commented
> Unutar baze imam dva admina sa emailom [fmadmin@vegait.rs](mailto:fmadmin@vegait.rs)

Separate issue is created for this. It will be resolved there.

2022-08-30 14:40 UTC, d-vucetic approved these changes

2022-08-30 14:40 UTC, merged